#!/bin/bash
set -euo pipefail

run() {
    if [ -z "$quiet" ]; then
        echo >&2 "+ $*"
    fi
    "$@"
}

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") [OPTIONS...] FILE

Open a web browser to look at the named FILE on Github on the current branch.

This is like \`hub browse\`, but actually knows where to find files on Github,
and handles relative paths correctly.

Options:
  -u, --url-only    Print URL rather than opening browser
  -h, --help        Show this help message
  -q, --quiet       Be less verbose

EOM
}

quiet=
url_only=

while [ $# -gt 0 ] && [[ "$1" = -* ]]; do
    case "$1" in
        -h|--help)
            usage
            exit
            ;;
        -u|--url-only)
            url_only=1
            ;;
        -q|--quiet)
            quiet=1
            ;;
        *)
            echo >&2 "Error: unexpected option $1"
            usage
            exit 1
            ;;
    esac
    shift
done


if [ $# -ne 1 ]; then
    echo "FILE is required"
    usage
    exit 1
fi

filename="$1"

# Get tree URL for this repo and branch
repo_tree_url="$(run hub browse -u -- tree)"

# Find the path to the requested file
full_path="$(run git ls-tree --full-name --name-only HEAD "$filename")"

# If the requested file is a directory, then ls-tree will have returned a list
# of filenames. Call dirname on the first one.
if [ -d "$filename" ]; then
    full_path="$(run dirname "$(head -1 <<< "$full_path")")"
    prefix="$repo_tree_url"
else
    # replace "tree" with "blob" since we are looking at a file
    prefix="${repo_tree_url/\/tree\///blob/}"
fi

full_url="$prefix/$full_path"

if [ -n "$url_only" ]; then
    echo "$full_url"
    exit
fi


if type -t xdg-open >/dev/null; then
    run xdg-open "$full_url"
    exit
fi

if type -t open >/dev/null; then
    run open "$full_url"
    exit
fi

echo >&2 "Error: couldn't find open or xdg-open to load a browser with"
exit 2
